version: "3"
services:
  app_python:
    image: marufasatullaev/app_python:latest
    build: app_python
    volumes:
      - volume-python:/app/volume
    expose:
      - 5000
    ports:
      - 5000:5000

volumes:
  volume-python:
